### ISSUE TITLE
Add digest info in intermediate bundle info

### ISSUE THREAD

**Issue by migmartri** [vmware-tanzu/asset-relocation-tool-for-kubernetes#102]
It will be great if we could add the image digest next to the image FQDN. We should follow the same format shown in the imageMoves section during a regular relocation

```
Will archive Helm Chart wordpress@12.2.3, dependent images and hint file to intermediate tarball "/tmp/intermediate.tar"
7 images detected to be archived:
gcr.io/sys-2b0109it/demo/bitnami/memcached-exporter:0.9.0-centos-7-r238
gcr.io/sys-2b0109it/demo/bitnami/wordpress:5.8.2-centos-7-r19
gcr.io/sys-2b0109it/demo/bitnami/apache-exporter:0.10.1-centos-7-r74
gcr.io/sys-2b0109it/demo/bitnami/tac-shell:7
gcr.io/sys-2b0109it/demo/bitnami/mariadb:10.5.13-centos-7-r0
gcr.io/sys-2b0109it/demo/bitnami/mysqld-exporter:0.13.0-centos-7-r158
gcr.io/sys-2b0109it/demo/bitnami/memcached:1.6.12-centos-7-r56

```

cc/ @josvazg

**Comment by josvazg** [comment]
Still pending here:
- Rename CLI flag `--to-archive` to `--to-intermediate`
- Add caching to the **save** operation so it is efficient when used for a bunch of charts. The cache must survive runs to be useful, so it must use a well known temporary directory.
