### ISSUE TITLE
Review airgap performance vs a regular move

### ISSUE THREAD

**Issue by josvazg** [vmware-tanzu/asset-relocation-tool-for-kubernetes#104]
Doing a airgap save operation to a local tar archive we noticed it to be much slower that moving the same chart directly with the regular move operation.

This issue is to check the reason behind such behavior. Can the save operation be improved somehow? Was the move using some cache somewhere?

**Comment by josvazg** [comment]
My suspicion is that the [go-containerregistry](https://github.com/google/go-containerregistry) library and the registries implementations are smart enough so that "moving" a layer from one repository to another in the same registry is almost free or at least a very cheap operation as the data is already under the same registry.

So we should make sure we compare the airgap operations vs a relocation to different registries.

**Comment by josvazg** [comment]
Summary of what I think is going on before we actually verify it:

Airgap **Save**: **All layers referenced are downloaded at least once** into the tarball, which starts empty.
Airgap **Load**: **ONLY layers missing in the target registry are uploaded**. Any test repetition with the same chart or repeated images will have a better performance, as some layers do not need to be uploaded, only metadata is replicated.

Move **Pull**: **No layers are downloaded ever**. Only the metadata, including digests, is downloaded. The image is kept as a remote reference and layers would only be downloaded if actually needed to use the image.
Move **Push** (=**Load**): **ONLY layers missing in the target registry are uploaded**.

To test airgap save/load performance vs a regular move in equal footing we need to use a fresh target registry every time so that:
- We avoid the chance of layers already been in the target, reference from another repo. Basically to any other previous push.

I can extend the registry test to verify this and measure relative impact.

**Comment by josvazg** [comment]
BTW note **we expect airgap to be twice as slow as a normal move** as the layers are moved twice, while the same direct move will only move layers once from source registry to destination registry at push time.

**Comment by migmartri** [comment]
> BTW note we expect airgap to be twice as slow as a normal move as the layers are moved twice,

Can you elaborate more why do we move the layers twice? Do you mean that we move it to a local temp tar and from that tar to inside the bundle?

in any case, to me, that does not mean that's going to take double the time since the issue under discussion is the fact that when using to-archive, the images get pulled always while when using the regular move the system seems to leverage local cache.

**Comment by josvazg** [comment]
> in any case, to me, that does not mean that's going to take double the time since the issue under discussion is the fact that when using to-archive, the images get pulled always while when using the regular move the system seems to leverage local cache.

I **do not think there is any local cache** involved here. Such cache is not needed, that is the magic os immutable content addressed image layers. Here is my reasoning:

- When we "pull" the images on a **move preparation step** (the equivalent of the save step) the images are not used, so their layers are not really downloaded. We only check the metadata and digest which is tiny in comparison and takes a small amount of time and bandwidth.
- When **you finish the move, layers might not need to be downloaded and re-uploaded because they might already exist in that registry**, even on another repository. In fact, as we usually always tests the same registries, and sometimes the origin and destination registry is the same, the data does not need to move, and if it needs to be copied at all it is a local copy inside the registry.
  - **The only way to force the move to actually move layer bytes is to make sure the target registry does not already contain the layers we are moving**.

And this takes us to the save/load scenario. On a **save and load we are almost always in the move to a target that does not know the images scenario**:
- On save the local bundle tar starts empty so it does need to download the image layers for sure.
- On loading the bundle to move the images to a new location, in real scenarios we are uploading layers again in most cases as the target registry is more unlikely to have seen those layers before.

I have run a couple of tests on a branch that I will post now for review. The numbers seems to add up, but still we can probably get some logs to ensure the above reasoning is what is happening.

On my tests I run a move against a fresh (empty) local registry, so we ensure the move actually does upload layers. And we also compare that to a full save/load against another target registry, run on a separate container launch, so it is fresh again.

The move took 63s and then 43s on one test, but the save/load test took 83s vs the 63s of the move on the first test and 55s vs 43s on the second test. Not sure about the variance between tests, and also save/load is not exactly 2 times the move, but it is about a 50% more time.

**Comment by josvazg** [comment]
Related PR #105
