### ISSUE TITLE
Tags should start with `v`

### ISSUE THREAD

**Issue by petewall** [vmware-tanzu/asset-relocation-tool-for-kubernetes#108]

**Comment by migmartri** [comment]
Agreed, but they should be added only if we cut a release and it should not happen in every commit. 

I'd personally remove the current tagging logic/automation from the CI and move to goreleaser to cut releases on explicit v.x tags

**Comment by migmartri** [comment]
Non valid anymore since the releases are now handled by goreleaser https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/115
