### ISSUE TITLE
Explicitly vendor and fix subcharts

### ISSUE THREAD

**Issue by migmartri** [vmware-tanzu/asset-relocation-tool-for-kubernetes#142]
Currently, if a Helm Chart requires some dependent charts, relok8s expects these dependencies to be already vendored at `[chart-root]/charts` directory. That's usually the case when the provided chart comes in package format (tar.gz)

A Helm chart, apart of the `charts` directory also contains the dependency references inside Chart.yaml and Chart.lock files, this files are useful when an user wants to update the deps via `helm dep update` but it can be problematic in the context of a relocation.

When relok8s move a Helm Chart, it will just move **only** this parent chart (including their vendored dependencies inside) to the new location, this will potentially leave a Chart.yaml file pointing to the wrong location and enabling the following potential issues.

* [ux] Chart explorer such as the one in Harbor will tell you that the dependencies are pointing somewhere else, when in fact the chart is fully functional already due to having the charts vendored.
* [security] An user could potentially run `helm dep update` and bring content from other sources i.e public repository
* [functional] Bringing a new version of a chart via helm dep update will override any relocation changes provided by the tool

That's why in my opinion relok8s should treat relocated Charts as immutable units, never meant to be upgraded. This could be achieved if relok8s removed as part of the relocation process the chart.lock files as well as the `dependencies:` entry in the Chart.yaml.

By doing so we will achieve

* UIs will not show false references
* `helm dep update` will fail as expected, so we added some guardrails that enforces the immutable nature of the asset

NOTE: This change will not affect charts-syncer since in fact this tool is not iterating on dependencies in this case.

cc/ @tompizmor @josvazg

**Comment by tompizmor** [comment]
Agree! I think those three reasons are enough to justify removing the dependencies from Chart.yaml. Have you though on the Chart.yaml/Chart.lock of the vendored dependencies?

>[ux] Chart explorer such as the one in Harbor will tell you that the dependencies are pointing somewhere else, when in fact the chart is fully functional already due to having the charts vendored.

I didn't know Harbor did that. How is that shown in the UI?

**Comment by migmartri** [comment]
It looks something like this for WordPress visualizing it in Harbor.

![image](https://user-images.githubusercontent.com/24523/152946724-4f495f79-b335-48bc-9c0e-25ffaeb07e29.png)

>  Have you though on the Chart.yaml/Chart.lock of the vendored dependencies?

I have not actually but you raise a great point. The 2nd and 3rd problem affects to subcharts indeed.

Thanks!!
