### ISSUE TITLE
Airgap, environment scenario

### ISSUE THREAD

**Issue by petewall** [vmware-tanzu/asset-relocation-tool-for-kubernetes#15]
One of the [core requirements](https://docs.google.com/document/d/18E58PJ0FGXWKiYXtvRdOi7wf6b4_vpL_dTLrNEZ6DZU/edit#bookmark=id.bmyycn3psn98) of this tool is to be able to relocate an asset in an air-gap environment scenario. Meaning that the source registries where the Chart and Container images are located, are not accessible from the destination environment.   

Currently, the tool does the relocation process e2e by pulling the images from source and pushing them to destination. This requires network access and credentials for both source and destination container repositories (and soon Helm chart repositories).

The goal of this task is to think about how to optionally support performing the relocation process potentially in multi-step fashion.

Functionally speaking this could look something like:

### Source Env

Run partial relocation that will
 
a) Pull source images

b) Pull Helm Charts

c) Store a + b + images-metadata.yaml file in an artifacts that could be taken to the airgapped env.

### Destination, airgapped environment 

Run partial relocation using the artifact generated in c. This will

d) Push images to destination registry

e) Rewrite Helm Chart(s)

e) Push Helm Chart (if applicable and once feature is available)

Some food for thought

* Re: Artifact create in C. We could look into creating a tarball, an OCI artifact, or even an imgkpg bundle. OCI is specially interesting to enable provenance.

**Comment by migmartri** [comment]
> > OCI is specially interesting to enable provenance.
> 
> You mean that format will allow is to state and track the origin of the charts and containers within I guess. Right?

What I mean is that by creating intermediate assets in OCI format, it could leverage signing via notary, or [cosign](https://github.com/sigstore/cosign)

**Comment by josvazg** [comment]
Going to try to have a diff today with the tar generation step.

**Comment by josvazg** [comment]
#82 **Support chart offline archival** is ready for review now, in fact, it already got one approval. That should cover the first step, packing up a chart with all its dependencies on an offline archive.

While I get the archival step reviewed to be merged, I will start working on the second step of deploying the chart and container images to the new locations at destination.

**Comment by josvazg** [comment]
Still pending here:

- Rename CLI flag --to-archive to --to-intermediate
- Add caching to the save operation so it is efficient when used for a bunch of charts. The cache must survive runs to be useful, so it must use a well known temporary directory.
- Document save/load use cases in samples.

**Comment by josvazg** [comment]
Actually there is a PR still about this related to the caching and its testing.

**Comment by josvazg** [comment]
PR #118 was just landed closing this
(#119 was abandoned in favor of #118)
