### ISSUE TITLE
Add examples directory

### ISSUE THREAD

**Issue by migmartri** [vmware-tanzu/asset-relocation-tool-for-kubernetes#21]
It would be useful to have an examples directory where we put a Helm Chart (or instructions on how to get it) + images rules file

**Comment by petewall** [comment]
Started working on this by moving the example pipeline over:
c4f91f0

**Comment by petewall** [comment]
More examples: 443ad08

**Comment by petewall** [comment]
b455af4 and the initial set of examples is done.

**Comment by migmartri** [comment]
These examples are very good!
