### ISSUE TITLE
Be consistent with output verb tense

### ISSUE THREAD

**Issue by migmartri** [vmware-tanzu/asset-relocation-tool-for-kubernetes#34]
When the command is run, the information showed in the prompt are in both past and future tense. 

```
Images to be pushed:
...

Changes written to mariadb/values.yaml:
...
Would you like to proceed? (y/N)
```
`Changes written` is in fact missleading since no change has happened yet. We should change this wording to make it conditional/future.

**Comment by migmartri** [comment]
> Hey,
> I think it should be `Changes to be written to mariadb/values.yaml:`. What do you think about this?

That looks reasonable, thanks!

**Comment by guptasajal411** [comment]
Can you tell me in which file this has to be changed, so that I can make a PR
