### ISSUE TITLE
Make a 5 min demo video

### ISSUE THREAD

**Issue by petewall** [vmware-tanzu/asset-relocation-tool-for-kubernetes#7]
Make a demo video, suitable for sharing or for posting on #mapbu-lightning-demos.

**Comment by petewall** [comment]
Working on a script:

<Show intro slide>
The Asset Relocation Tool for Kubernetes is a useful utility for moving Kubernetes assets. Our first use case focuses on Helm charts.

<Show slide about helm charts>
Helm charts deploy workloads onto a Kubernetes cluster by templating Pods, ReplicaSets, Deployments or other formats. Those templates will specify a container image to use for the pods that will be instantiated. However, the operator installing the Helm chart must rely that the external source of those images will remain accessible and unaltered:

<show slide of problems>
* Container images can be removed from the registry
* Developers can upload new images with an existing tag

As well, using external images is not workable for solutions that require private registries.

<Show slide of potential workarounds>
It would be great to use the carvel toolset, which solve lots of these problems, but VMware and our customers will always encounter Helm charts from 3rd party sources, like open source charts or ISV partners.

Helm charts will allow operators to override values when deploying, but that would require keeping those overrides somewhere along with the chart, so it is used consistently with every install.

<Show slide of relok8s>
The Asset Relocation Tool for Kubernetes can:
1. find all the container images referenced in a Helm chart
2. modify their image references to use a new image registry or repository path
3. push those images to the new registry
4. and write a new Helm chart with the modified image references.

This solution is portable because all changes are encapsulated in the modified chart. It is flexible for different kinds of installations because all images are rewritten, regardless of the rendering.

<Show terminal>
I'll now show a demonstration of the tool, using `relok8s`, the command-line interface.

Here, I have a Helm chart for (Wordpress?). You can see that it has ___ sub charts. Using this command <some kind of find and grep>, I can see that there are __ images referenced in this helm chart. Not all of these images would be deployed, however, because some are only used when certain features are enabled. <show values.yaml file> Here is where those values are located

To help relok8s find the images, we create an image hints file. This file will be rendered using the chart's `values.yaml` file.

Now, I'll run relok8s with the chart, the image hints file and I'll specify the new registry and modifications to the repository path.

... <further discussion of relok8s output>

The result is this Helm chart, which has the image reference modifications written directly to the new values.yaml file.

<some sort of epilogue?>

**Comment by josvazg** [comment]
LGTM so far

**Comment by petewall** [comment]
Delivered!
